spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_bookstore?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
      username: root
      password: xlzhao.123
# Mybatis Plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto